# Generated by Django 6.0.5 on 2026-06-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
